### ISSUE TITLE
Bug: undefined with Object validation

### ISSUE THREAD

**Issue by jy95** [oxyno-zeta/express-joi-middleware#1]
#### Context

* *node version*: 6.10.3
* *joi version*: ^10.2 (current : 10.3.4 )
* *environment* (node, browser): node
* *used with* (hapi, standalone, ...): express
* *any other relevant information*: (used by express-joi-middleware@^1.0.0)

#### What are you trying to achieve or the steps to reproduce ?

Describe your issue here, include schemas and inputs you are validating if needed.

I used this joi schema for validate a form : 
```
{
        body: {
            // RFC 3399 regex : https://gist.github.com/marcelotmelo/b67f58a08bee6c2468f8
            dateTime: Joi.string().regex(/^([0-9]+)-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])[Tt]([01][0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9]|60)(\.[0-9]+)?(([Zz])|([\+|\-]([01][0-9]|2[0-3]):[0-5][0-9]))$/).required(),
            call_id: Joi.number().integer().positive().required(),
            eventCategory: Joi.number().integer().positive().required(),
            extra: Joi.object().required()
        }
}
```
So I used this data : 
```json
{
"dateTime" : "2017-05-15T17:22:55+02:00",
"eventCategory" : 1,
"call_id" : 4,
"extra": {
   "gateId": 57
}
}
```

#### Which result you had ?
undefined
#### What did you expect ?
```json
{
"dateTime" : "2017-05-15T17:22:55+02:00",
"eventCategory" : 1,
"call_id" : 4,
"extra": {
   "gateId": 57
}
}
```

#### Culpit 

By @WesTyler , this is the cause :  https://github.com/hapijs/joi/issues/1187#issuecomment-301636553 )

> Ok, so you are getting undefined as the return value from express-joi-middleware, and that's the main problem, right?
>If so I think I found why. It looks like the middleware isn't providing you with the result of validation, it is just "decorating" the original request object:
(via https://github.com/oxyno-zeta/express-joi-middleware/blob/c57fe0be68f89f8bd3fe854d3d66688022f75852/index.js#L60-L63)
```js
const extendObject = {};
extendObject[key] = value;
Object.assign(req, extendObject);

// Go to next
next();
```

#### Bonus 

I suggest you to change your copy function by something recursive , like https://www.npmjs.com/package/extend (with deep argument set to true)

When I check with console.log in req.validated.body : 
```
{
        "dateTime" : "2017-05-15T17:22:55+02:00",
        "eventCategory" : 1,
        "call_id" : 4,
        "extra": {
            "gateId": 57
}
```

**Comment by WesTyler** [comment]
I don't actually think the `undefined` issue is a bug in behavior here. I think it was a mismatch in expectations.

@jy95, after the validation middleware does its thing, where is `undefined` coming from? Is it a `return`ed value, are you accessing a property on the request object to check the validation result, or is this an HTTP response paylodd?

**Comment by jy95** [comment]
It is the result of the validation. (validated version: req.validated.body, original : req.body)
Strange, I got no issue when I have simple properties ... This issue occurs with nested properties ...

**Comment by oxyno-zeta** [comment]
@jy95 @WesTyler  : I don't understand well I think.
I test by myself with this code:
```js
const regexIssue1 = /^([0-9]+)-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])[Tt]([01][0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9]|60)(\.[0-9]+)?(([Zz])|([\+|\-]([01][0-9]|2[0-3]):[0-5][0-9]))$/;
app.post('/issues-1', library({
    body: {
        // RFC 3399 regex : https://gist.github.com/marcelotmelo/b67f58a08bee6c2468f8
        dateTime: Joi.string().regex(regexIssue1).required(),
        call_id: Joi.number().integer().positive().required(),
        eventCategory: Joi.number().integer().positive().required(),
        extra: Joi.object().required(),
    },
}), (req, res) => {
    const body = req.validated.body;
    res.send('Ok');
});

app.listen(3000, () => {
    console.log('listen');
});

```
And these versions:
- joi: 10.3.4
- node: 6.10.3

I post this body:
```js
{
	"dateTime" : "2017-05-15T17:22:55+02:00",
	"eventCategory" : 1,
	"call_id" : 4,
	"extra": {
		"gateId": 57
	}
}
```

And in `req.validated.body` and `body` (with debugger), I found:
```js
{
  "dateTime": "2017-05-15T17:22:55+02:00",
  "eventCategory": 1,
  "call_id": 4,
  "extra": {
    "gateId": 57
  }
}
```

____________________________________________________________________

I just tested with extend. It give the same result.

@WesTyler : Can you explain me where is the problem ?

Thanks !

**Comment by oxyno-zeta** [comment]
I just created a Gitter if you want. I think this can be easier :)
https://gitter.im/express-joi-middleware/

**Comment by WesTyler** [comment]
> Can you explain me where is the problem ?

I don't think there is one :). I think that there was just a misunderstanding on where the validation result ends up being added onto the request object (`req.validated.body`).

**Comment by oxyno-zeta** [comment]
I also try with this code:
```js
const regexIssue1 = /^([0-9]+)-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])[Tt]([01][0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9]|60)(\.[0-9]+)?(([Zz])|([\+|\-]([01][0-9]|2[0-3]):[0-5][0-9]))$/;
app.post('/issues-1', library({
    body: {
        // RFC 3399 regex : https://gist.github.com/marcelotmelo/b67f58a08bee6c2468f8
        dateTime: Joi.string().regex(regexIssue1).required(),
        call_id: Joi.number().integer().positive().required(),
        eventCategory: Joi.number().integer().positive().required(),
        extra: Joi.object().required(),
    },
}, { wantResponse: true }), (req, res) => {
    const body = req.validated.body.extra.gateId;
    console.log(body);
    res.send('Ok');
});
```

The console print '57'.

**Comment by oxyno-zeta** [comment]
I think I understand now !
@WesTyler is saying right !
@jy95  : The validation is done on `req.body` and the result is in `req.validated` (with default options) according to the schema gave to the middleware : 
```js
{
  body: {
    .....
  }
}
```

will create `req.validated.body`.

@jy95 : Is it ok on your side ? I can close the issue ?

**Comment by jy95** [comment]
So what should I change ?

The full error stack (addEventForCall.js is the place when I got this error) : 
```js
TypeError: Cannot read property 'body' of undefined
    at D:\workspaceNodeJs\helpdesk-admin\controllers\addEventForCall.js:22:38
    at Layer.handle [as handle_request] (D:\workspaceNodeJs\helpdesk-admin\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\workspaceNodeJs\helpdesk-admin\node_modules\express\lib\router\route.js:137:13)
    at D:\workspaceNodeJs\helpdesk-admin\node_modules\connect-ensure-login\lib\ensureLoggedIn.js:50:5
    at Layer.handle [as handle_request] (D:\workspaceNodeJs\helpdesk-admin\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\workspaceNodeJs\helpdesk-admin\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\workspaceNodeJs\helpdesk-admin\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\workspaceNodeJs\helpdesk-admin\node_modules\express\lib\router\layer.js:95:5)
    at D:\workspaceNodeJs\helpdesk-admin\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (D:\workspaceNodeJs\helpdesk-admin\node_modules\express\lib\router\index.js:335:12)
    at next (D:\workspaceNodeJs\helpdesk-admin\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (D:\workspaceNodeJs\helpdesk-admin\node_modules\express\lib\router\index.js:174:3)
    at router (D:\workspaceNodeJs\helpdesk-admin\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\workspaceNodeJs\helpdesk-admin\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\workspaceNodeJs\helpdesk-admin\node_modules\express\lib\router\index.js:317:13)
    at D:\workspaceNodeJs\helpdesk-admin\node_modules\express\lib\router\index.js:284:7
```

**Comment by oxyno-zeta** [comment]
Can you show your code ? (A sample)
Thanks !

**Comment by jy95** [comment]
You can close this issue : I finally found inside some config a "/" was missing and so no schema was loaded.

**Comment by oxyno-zeta** [comment]
Great !! I was going crazy with this :). Thanks !
